# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BSSIDApple.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='BSSIDApple.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x10\x42SSIDApple.proto\"q\n\x07WifiGeo\x12\r\n\x05\x62ssid\x18\x01 \x01(\t\x12#\n\x08location\x18\x02 \x01(\x0b\x32\x11.WifiGeo.Location\x1a\x32\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x03\x12\x0b\n\x03lon\x18\x02 \x01(\x03\x12\x0c\n\x04unk1\x18\x03 \x01(\x03\"^\n\tBSSIDResp\x12\x0c\n\x04unk1\x18\x01 \x01(\x03\x12\x16\n\x04wifi\x18\x02 \x03(\x0b\x32\x08.WifiGeo\x12\x0c\n\x04unk2\x18\x03 \x01(\x05\x12\x0c\n\x04unk3\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\tb\x06proto3'
)

_WIFIGEO_LOCATION = _descriptor.Descriptor(
    name='Location',
    full_name='WifiGeo.Location',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='lat', full_name='WifiGeo.Location.lat', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='lon', full_name='WifiGeo.Location.lon', index=1,
            number=2, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='unk1', full_name='WifiGeo.Location.unk1', index=2,
            number=3, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=83,
    serialized_end=133,
)

_WIFIGEO = _descriptor.Descriptor(
    name='WifiGeo',
    full_name='WifiGeo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='bssid', full_name='WifiGeo.bssid', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='location', full_name='WifiGeo.location', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[_WIFIGEO_LOCATION, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=20,
    serialized_end=133,
)

_BSSIDRESP = _descriptor.Descriptor(
    name='BSSIDResp',
    full_name='BSSIDResp',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='unk1', full_name='BSSIDResp.unk1', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='wifi', full_name='BSSIDResp.wifi', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='unk2', full_name='BSSIDResp.unk2', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='unk3', full_name='BSSIDResp.unk3', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='APIName', full_name='BSSIDResp.APIName', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=135,
    serialized_end=229,
)

_WIFIGEO_LOCATION.containing_type = _WIFIGEO
_WIFIGEO.fields_by_name['location'].message_type = _WIFIGEO_LOCATION
_BSSIDRESP.fields_by_name['wifi'].message_type = _WIFIGEO
DESCRIPTOR.message_types_by_name['WifiGeo'] = _WIFIGEO
DESCRIPTOR.message_types_by_name['BSSIDResp'] = _BSSIDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WifiGeo = _reflection.GeneratedProtocolMessageType('WifiGeo', (_message.Message,), {

    'Location': _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
        'DESCRIPTOR': _WIFIGEO_LOCATION,
        '__module__': 'BSSIDApple_pb2'
        # @@protoc_insertion_point(class_scope:WifiGeo.Location)
    })
    ,
    'DESCRIPTOR': _WIFIGEO,
    '__module__': 'BSSIDApple_pb2'
    # @@protoc_insertion_point(class_scope:WifiGeo)
})
_sym_db.RegisterMessage(WifiGeo)
_sym_db.RegisterMessage(WifiGeo.Location)

BSSIDResp = _reflection.GeneratedProtocolMessageType('BSSIDResp', (_message.Message,), {
    'DESCRIPTOR': _BSSIDRESP,
    '__module__': 'BSSIDApple_pb2'
    # @@protoc_insertion_point(class_scope:BSSIDResp)
})
_sym_db.RegisterMessage(BSSIDResp)

# @@protoc_insertion_point(module_scope)
